#! /bin/bash
# (\ /)  simpler
# ( . .)  fetch script
# c(*)(*)  written in bash by c:
#
# goal of this script is to be short
# and to be easy to read and edit
# to suit user's taste.

## escape seqs for colors.
C1='\033[1;31m'
C2='\033[1;32m'
C3='\033[1;33m'
C4='\033[1;34m'
C5='\033[1;35m'
C6='\033[1;36m'
CC='\033[0;30m'
BB='\033[1m'
esc='\e[0m'
H='██'  # color char (U+2588 - full block)

## ascii art line by line
## it's recommended to end lines with _${esc}_
## if ascii art has colors. it's done to not mess up
## text colors with art colors.
A1="${C1}        <3        ${esc}"
A2="${CC}       /  \       ${esc}"
A3="${C4} (\ /)   ${C5}  (\ (\  ${esc}"
A4="${C4} ( . .)  ${C5}  (. . ) ${esc}"
A5="${C4} c(*)(*) ${C5} (*)(*)o ${esc}"

##         art  columns: info
echo
echo -e " ${A1}      ${BB}$USER@$HOSTNAME${esc}"
echo -e " ${A2}      os: $OSTYPE"  # or $(lsb_release -sd) for distro name
echo -e " ${A3}   wm/de: ${XDG_SESSION_DESKTOP^}"  # or $DESKTOP_SESSION
echo -e " ${A4}  editor: $EDITOR"
echo -e " ${A5}    cols: ${C1}${H}${C2}${H}${C3}${H}${C4}${H}${C5}${H}${C6}${H}${esc}"
echo
